# Do NOT update manually; changes here will be overwritten by Copier
_commit: ea28867
_src_path: /opt/odoo-projects/var/oca-addons-repo-template/
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 14.0
org_name: IT-Projects LLC
org_slug: it-projects-llc
rebel_module_groups: []
repo_description: ''
repo_name: ''
repo_slug: tg-addons
repo_website: https://github.com/it-projects-llc/tg-addons
use_pyproject_toml: false
use_ruff: false

