import logging

_logger = logging.getLogger(__name__)


def post_load():
    from odoo.addons.sale_loyalty.models.sale_order import (
        SaleOrder,
        _,
        defaultdict,
        float_is_zero,
    )

    def _apply_program_reward(self, reward, coupon, **kwargs):
        """
        Applies the reward to the order provided the given coupon has enough points.
        This method does not check for program rules.

        This method also assumes the points added by the program triggers have already been computed.
        The temporary points are used if the program is applicable to the current order.

        Returns a dict containing the error message or empty if everything went correctly.
        NOTE: A call to `_update_programs_and_rewards` is expected to reorder the discounts.
        """
        self.ensure_one()
        # Use the old lines before creating new ones. These should already be in a 'reset' state.
        old_reward_lines = kwargs.get('old_lines', self.env['sale.order.line'])
        if reward.is_global_discount:
            global_discount_reward_lines = self._get_applied_global_discount_lines()
            global_discount_reward = global_discount_reward_lines.reward_id
            # changes start
            is_global_discount_accumulative = any(global_discount_reward.mapped("program_id.is_accumulative"))
            global_discount_exceeds_reward = any([gdr.discount >= reward.discount for gdr in global_discount_reward])
            if global_discount_reward and global_discount_reward != reward and global_discount_exceeds_reward and is_global_discount_accumulative is False and reward.program_id.is_accumulative is False:
                return {'error': _('A better global discount is already applied.')}
            elif global_discount_reward and global_discount_reward != reward and (is_global_discount_accumulative is False or reward.program_id.is_accumulative is False):
                # Invalidate the old global discount as it may impact the new discount to apply
                global_discount_reward_lines._reset_loyalty(True)
                old_reward_lines |= global_discount_reward_lines
            # changes end
        if not reward.program_id.is_nominative and reward.program_id.applies_on == 'future' and coupon in self.coupon_point_ids.coupon_id:
            return {'error': _('The coupon can only be claimed on future orders.')}
        elif self._get_real_points_for_coupon(coupon) < reward.required_points:
            return {'error': _('The coupon does not have enough points for the selected reward.')}
        reward_vals = self._get_reward_line_values(reward, coupon, **kwargs)
        self._write_vals_from_reward_vals(reward_vals, old_reward_lines)
        return {}

    SaleOrder._apply_program_reward = _apply_program_reward

    def _get_claimable_rewards(self, forced_coupons=None):
        """
        Fetch all rewards that are currently claimable from all concerned coupons,
         meaning coupons from applied programs and applied rewards or the coupons given as parameter.

        Returns a dict containing the all the claimable rewards grouped by coupon.
        Coupons that can not claim any reward are not contained in the result.
        """
        self.ensure_one()
        all_coupons = forced_coupons or (self.coupon_point_ids.coupon_id | self.order_line.coupon_id | self.applied_coupon_ids)
        has_payment_reward = any(line.reward_id.program_id.is_payment_program for line in self.order_line)
        total_is_zero = float_is_zero(self.amount_total, precision_digits=2)
        result = defaultdict(lambda: self.env['loyalty.reward'])
        global_discount_reward = self._get_applied_global_discount()
        active_products_domain = self.env['loyalty.reward']._get_active_products_domain()
        for coupon in all_coupons:
            # Skip coupons generated by this order that only apply on future orders
            if coupon.program_id.applies_on == 'future' and coupon.order_id == self:
                continue
            points = self._get_real_points_for_coupon(coupon)
            for reward in coupon.program_id.reward_ids:
                # changes start
                is_global_discount_accumulative = any(global_discount_reward.mapped("program_id.is_accumulative"))
                global_discount_exceeds_reward = any([gdr.discount >= reward.discount for gdr in global_discount_reward])
                if reward.is_global_discount and global_discount_reward and global_discount_exceeds_reward and is_global_discount_accumulative is False and reward.program_id.is_accumulative is False:
                    continue
                # changes end

                # Discounts are not allowed if the total is zero unless there is a payment reward, in which case we allow discounts.
                # If the total is 0 again without the payment reward it will be removed.
                is_discount = reward.reward_type == 'discount'
                is_payment_program = reward.program_id.is_payment_program
                if is_discount and total_is_zero and (not has_payment_reward or is_payment_program):
                    continue
                # Skip discount that has already been applied if not part of a payment program
                if is_discount and not is_payment_program and reward in self.order_line.reward_id:
                    continue
                if reward.reward_type == 'product' and not reward.filtered_domain(
                    active_products_domain
                ):
                    continue
                if points >= reward.required_points:
                    result[coupon] |= reward
        return result

    SaleOrder._get_claimable_rewards = _get_claimable_rewards
